# services:
#   chromadb:
#     image : chromadb/chroma
#     ports:
#      - 8000:8000

# #     volumes:
# #      - chromadb_data:/data


# # volumes:
# #   chromadb_data:

services:
  pinecone:
    image: ghcr.io/pinecone-io/pinecone-local:latest
    environment: 
      PORT: 5080
      PINECONE_HOST: localhost
    ports: 
      - "5080-5090:5080-5090"
    platform: linux/amd64